### ISSUE TITLE
New MVA Stream Unit with int2 inputs

### ISSUE THREAD

**Issue by auphelia** [Xilinx/finn-hlslib#11]
When using the Matrix_Vector_Activate_Stream_Batch function from mvau.hpp the weights and input values are not correctly sliced. Please find attached an example of a failing testcase. Maybe there is an error in the setting of the template parameter. The inputs and weights are saved in .npy files and read out using functions from [npy2apintstream.hpp](https://github.com/Xilinx/finn/blob/dev/src/finn/data/cpp/npy2apintstream.hpp). 

[code_gen_npysim_MVASU.zip](https://github.com/Xilinx/finn-hlslib/files/4313603/code_gen_npysim_MVASU.zip)

**Comment by giuliogamba** [comment]
Can you please check with the latest commit? Please note a change in the template values (as per example [here](https://github.com/Xilinx/finn-hlslib/blob/master/tb/conv_stream_top.cpp)).
