### ISSUE TITLE
Using ap_fixed for convolution

### ISSUE THREAD

**Issue by sktalha68** [Xilinx/finn-hlslib#125]
Can we use ap_fixed datatypes for weights, inputs and output streams? The function by default only accept ap_uint.

**Comment by preusser** [comment]
I assume you're planning to use the hlslib function standalone without relying on the FINN compiler?
Then you are free to use whatever data interpretation you might choose. The `ap_uint` type is merely a transport container. The semantics are defined by the interpreting functor types specified as the template parameters `TSrcI`, `TDstI` and `TWeightI`.
