### ISSUE TITLE
fatal error: memdata.h

### ISSUE THREAD

**Issue by yingsto** [Xilinx/finn-hlslib#14]
messages:
 
  Compiling ../../../../conv3_tb.cpp in debug mode
../../../../conv3_tb.cpp:51:21: fatal error: memdata.h:

**Comment by giuliogamba** [comment]
Can you please give more information about your problem? If there is no memdata.h file, it's possible you haven't executed the [gen_weigths.py](https://github.com/Xilinx/finn-hlslib/blob/master/tb/gen_weigths.py) script which generates the random paramenters for the convolution.

**Comment by yingsto** [comment]
@giuliogamba  Thanks! You are right.  After I executed gen_weigths.py script, the memdata.h file was generated.
