### ISSUE TITLE
ERROR: [SIM 211-100] Csim failed with error

### ISSUE THREAD

**Issue by NguyenD-Nam** [Xilinx/finn-hlslib#60]
Hello, I'm new to Vivado HLS, I run a simple C++ project and when I simulate, I get errors like these:
> 1 INFO: [SIM 2] *************** CSIM start ***************
> 2 INFO: [SIM 4] CSIM will launch GCC as the compiler.
> 3 ERR: [SIM 100] CSim failed with errors.
> 4 INFO: [SIM 3] *************** CSIM finish ***************

The console tab shows something like this:
```
"source /*path*/solution1/csim.tcl"
    invoked from within
"hls::main /*path*/solution1/csim.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel 1 hls::main {*}$args"
    (procedure "hls_proc" line 5)
    invoked from within
"hls_proc $argv"
Finished C simulation.
```

How can I fix this, thank you so much.

**Comment by maltanar** [comment]
Hi @NguyenD-Nam , this issue tracker is for finn-hlslib bugs. Please follow the [Xilinx Vitis HLS tutorials](https://github.com/Xilinx/Vitis-HLS-Introductory-Examples) and use the [Xilinx support forum](https://support.xilinx.com/s/topic/0TO2E000000YKXtWAO/hls?language=en_US) for your question..
