### ISSUE TITLE
Sliding Window testbench not working with stride = 1

### ISSUE THREAD

**Issue by wady101** [Xilinx/finn-hlslib#8]
Hi authors, 
For file , tb/swg_tb.cpp. When I change STRIDE from 2 to 1 in tb/input_gen.h, I get this error: 

```
ERROR:  Expected 72 actual 60
oy= 0 ox= 0 ky= 0 kx= 0
WARNING: Hls::stream 'output_stream' contains leftover data, which may result in RTL simulation hanging.
WARNING: Hls::stream 'input_stream' contains leftover data, which may result in RTL simulation hanging.
@E Simulation failed: Function 'main' returns nonzero value '1'.
```

After some debugging I could see the error was when the counter is set to 44, it would throw up this error. 

Thanks!

**Comment by giuliogamba** [comment]
HI, 

that version of the input generator does not work when the kernel size (`ConvKernelDim`) is not multiple of the stride. I will add later an assert on this function and a new version which support arbitrary stride value.

**Comment by wady101** [comment]
Whoops forgot about that. Thanks!!
